# Generated by Django 5.1.4 on 2025-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='platform',
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='platforms',
            field=models.ManyToManyField(related_name='user_preferences', to='project_management.communicationplatform'),
        ),
    ]
