# Generated by Django 5.1.4 on 2025-01-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_usernotificationpreference_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='platform',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='project_management.task'),
        ),
        migrations.DeleteModel(
            name='TaskExtensionRequest',
        ),
    ]
